*-----------------------------------------------------------
* Title      : practical_06_part4
* Written by : Damon Kelly
* Date       : 02/03/2026
* Description: test trap task
*-----------------------------------------------------------
    ORG    $1000
START:                  ; first instruction of program

    LEA     $4000, SP
    
    MOVE.B  #1, -(SP)
    MOVE.B  #2, -(SP)
    MOVE.B  #3, -(SP)
    MOVE.B  #4, -(SP)
    
    MOVE.B  (SP)+, D1
    MOVE.B  (SP)+, D1
    MOVE.B  (SP)+, D1
    MOVE.B  (SP)+, D1

    SIMHALT             ; halt simulator



    END    START        ; last line of source

*~Font name~Courier New~
*~Font size~12~
*~Tab type~1~
*~Tab size~4~
